apiVersion: argonaut.metalabs.no/v1beta1
kind: Argonaut
metadata:
  name: testantino
  namespace: default
spec:
  argoTunnelName: "slartibartfast"
  cfAuthSecret:
    name: argonaut
    namespace: default
  ingress:
    - hostname: test.anti.no
      serviceSelector:
        matchLabels:
          app: nginx
    - hostname: test2.anti.no
      serviceSelector:
        matchLabels:
          app: nginx