apiVersion: argonaut.metalabs.no/v1beta1
kind: Argonaut
metadata:
  name: testantino
  namespace: default
spec:
  argoTunnelName: "test"
  cfAuthSecret:
    name: argonaut
    namespace: default
  ingress:
    - hostname: test.anti.no
      endpointsSelector:
        matchLabels:
          app: nginx