// +build !ignore_autogenerated

/*
Copyright 2021 The Argonaut authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Argonaut) DeepCopyInto(out *Argonaut) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Argonaut.
func (in *Argonaut) DeepCopy() *Argonaut {
	if in == nil {
		return nil
	}
	out := new(Argonaut)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Argonaut) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgonautIngressRule) DeepCopyInto(out *ArgonautIngressRule) {
	*out = *in
	in.EndpointsSelector.DeepCopyInto(&out.EndpointsSelector)
	in.ServiceSelector.DeepCopyInto(&out.ServiceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgonautIngressRule.
func (in *ArgonautIngressRule) DeepCopy() *ArgonautIngressRule {
	if in == nil {
		return nil
	}
	out := new(ArgonautIngressRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgonautList) DeepCopyInto(out *ArgonautList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Argonaut, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgonautList.
func (in *ArgonautList) DeepCopy() *ArgonautList {
	if in == nil {
		return nil
	}
	out := new(ArgonautList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgonautList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgonautSpec) DeepCopyInto(out *ArgonautSpec) {
	*out = *in
	out.ArgoTunnelSecret = in.ArgoTunnelSecret
	out.CFAuthSecret = in.CFAuthSecret
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]ArgonautIngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgonautSpec.
func (in *ArgonautSpec) DeepCopy() *ArgonautSpec {
	if in == nil {
		return nil
	}
	out := new(ArgonautSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgonautStatus) DeepCopyInto(out *ArgonautStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgonautStatus.
func (in *ArgonautStatus) DeepCopy() *ArgonautStatus {
	if in == nil {
		return nil
	}
	out := new(ArgonautStatus)
	in.DeepCopyInto(out)
	return out
}
